### ISSUE TITLE
Beta1 Release Checklist

### ISSUE THREAD

**Issue by aweingarten** [adweingarten/cloudflare#8]
### Business Requirements
- [ ] As a developer/sitebuilder I want a stable release of the CloudFlare module that provides cache-clearing functionality.
### Technical Requirements
- [x] Review composer.json to make sure that dependencies are appropriately pinned. 
- [x] Audit the readme.md
- [x] Tag a beta release. 
- [x] Get a release on D.O
- [ ] Add beta to packagist
